<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="1962 112.6 422.9 584" enable-background="new 1962 112.6 422.9 584" xml:space="preserve">
<g>
	<g>
		<path fill="#95A3FC" d="M173.1,799.7h4.7v58.2h36.9v4.2h-41.6V799.7z"/>
	</g>
	<g>
		
			<linearGradient id="SVGID_1_" gradientUnits="userSpaceOnUse" x1="33.8798" y1="855.8" x2="236.3007" y2="855.8" gradientTransform="matrix(5.1987 0 0 -5.1987 -3.1336 5279.9111)">
			<stop  offset="0" style="stop-color:#95A3FC"/>
			<stop  offset="2.983357e-02" style="stop-color:#82BFFB"/>
			<stop  offset="0.2927" style="stop-color:#51A6E9"/>
			<stop  offset="0.3265" style="stop-color:#43AED0"/>
			<stop  offset="0.3631" style="stop-color:#3AABC1"/>
			<stop  offset="0.3968" style="stop-color:#2799AD"/>
			<stop  offset="0.4306" style="stop-color:#2293A8"/>
			<stop  offset="0.4607" style="stop-color:#18879E"/>
			<stop  offset="0.5106" style="stop-color:#0F7397"/>
			<stop  offset="0.5495" style="stop-color:#0F7397"/>
			<stop  offset="0.589" style="stop-color:#0F7397"/>
			<stop  offset="0.6393" style="stop-color:#1A71A7"/>
			<stop  offset="0.68" style="stop-color:#2C71B3"/>
			<stop  offset="0.685" style="stop-color:#0F7696"/>
			<stop  offset="0.7185" style="stop-color:#6275D5"/>
			<stop  offset="0.739" style="stop-color:#6275D5"/>
			<stop  offset="0.7889" style="stop-color:#B350F5"/>
			<stop  offset="0.8268" style="stop-color:#C449F7"/>
			<stop  offset="0.9021" style="stop-color:#D957FE"/>
			<stop  offset="0.9792" style="stop-color:#E05DFE"/>
			<stop  offset="1" style="stop-color:#EC64FE"/>
		</linearGradient>
		<path fill="url(#SVGID_1_)" d="M173.1,799.7h4.7v58.2h36.9v4.2h-41.6V799.7z"/>
		
			<linearGradient id="SVGID_2_" gradientUnits="userSpaceOnUse" x1="33.8798" y1="855.55" x2="236.3007" y2="855.55" gradientTransform="matrix(5.1987 0 0 -5.1987 -3.1336 5279.9111)">
			<stop  offset="0" style="stop-color:#95A3FC"/>
			<stop  offset="2.983357e-02" style="stop-color:#82BFFB"/>
			<stop  offset="0.2927" style="stop-color:#51A6E9"/>
			<stop  offset="0.3265" style="stop-color:#43AED0"/>
			<stop  offset="0.3631" style="stop-color:#3AABC1"/>
			<stop  offset="0.3968" style="stop-color:#2799AD"/>
			<stop  offset="0.4306" style="stop-color:#2293A8"/>
			<stop  offset="0.4607" style="stop-color:#18879E"/>
			<stop  offset="0.5106" style="stop-color:#0F7397"/>
			<stop  offset="0.5495" style="stop-color:#0F7397"/>
			<stop  offset="0.589" style="stop-color:#0F7397"/>
			<stop  offset="0.6393" style="stop-color:#1A71A7"/>
			<stop  offset="0.68" style="stop-color:#2C71B3"/>
			<stop  offset="0.685" style="stop-color:#0F7696"/>
			<stop  offset="0.7185" style="stop-color:#6275D5"/>
			<stop  offset="0.739" style="stop-color:#6275D5"/>
			<stop  offset="0.7889" style="stop-color:#B350F5"/>
			<stop  offset="0.8268" style="stop-color:#C449F7"/>
			<stop  offset="0.9021" style="stop-color:#D957FE"/>
			<stop  offset="0.9792" style="stop-color:#E05DFE"/>
			<stop  offset="1" style="stop-color:#EC64FE"/>
		</linearGradient>
		<path fill="url(#SVGID_2_)" d="M278.1,852.7c-5.7,6.8-13,10.9-21.3,10.9c-10.9,0-19.2-7.3-19.2-17.2l0,0c0-8.3,6.2-14.6,16.1-18.2
			c-4.7-5.2-6.8-9.4-6.8-14.6l0,0c0-8.3,6.8-14,15.6-14c8.3,0,14.6,6.2,14.6,13.5l0,0c0,7.8-5.7,13-15.6,16.1l16.6,17.2
			c3.1-4.2,5.7-9.4,8.3-15.1l4.2,1.6c-3.1,6.2-5.7,12-9.4,16.6l11.4,12l-3.6,3.1L278.1,852.7z M275,849.6l-18.7-19.2
			c-9.9,3.6-14.6,9.4-14.6,15.1l0,0c0,7.8,6.2,13.5,14.6,13.5C264.1,859.5,269.8,855.8,275,849.6z M272.4,812.7L272.4,812.7
			c0-5.7-4.2-9.9-9.9-9.9c-6.2,0-10.9,4.7-10.9,9.9l0,0c0,4.2,1.6,6.8,7.3,13C267.7,823.1,272.4,818.4,272.4,812.7z"/>
		
			<linearGradient id="SVGID_3_" gradientUnits="userSpaceOnUse" x1="33.8798" y1="855.8" x2="236.3007" y2="855.8" gradientTransform="matrix(5.1987 0 0 -5.1987 -3.1336 5279.9111)">
			<stop  offset="0" style="stop-color:#95A3FC"/>
			<stop  offset="2.983357e-02" style="stop-color:#82BFFB"/>
			<stop  offset="0.2927" style="stop-color:#51A6E9"/>
			<stop  offset="0.3265" style="stop-color:#43AED0"/>
			<stop  offset="0.3631" style="stop-color:#3AABC1"/>
			<stop  offset="0.3968" style="stop-color:#2799AD"/>
			<stop  offset="0.4306" style="stop-color:#2293A8"/>
			<stop  offset="0.4607" style="stop-color:#18879E"/>
			<stop  offset="0.5106" style="stop-color:#0F7397"/>
			<stop  offset="0.5495" style="stop-color:#0F7397"/>
			<stop  offset="0.589" style="stop-color:#0F7397"/>
			<stop  offset="0.6393" style="stop-color:#1A71A7"/>
			<stop  offset="0.68" style="stop-color:#2C71B3"/>
			<stop  offset="0.685" style="stop-color:#0F7696"/>
			<stop  offset="0.7185" style="stop-color:#6275D5"/>
			<stop  offset="0.739" style="stop-color:#6275D5"/>
			<stop  offset="0.7889" style="stop-color:#B350F5"/>
			<stop  offset="0.8268" style="stop-color:#C449F7"/>
			<stop  offset="0.9021" style="stop-color:#D957FE"/>
			<stop  offset="0.9792" style="stop-color:#E05DFE"/>
			<stop  offset="1" style="stop-color:#EC64FE"/>
		</linearGradient>
		<path fill="url(#SVGID_3_)" d="M319.7,799.7h26.5c7.8,0,14,2.6,17.7,6.2c3.1,3.1,4.7,7.3,4.7,11.4l0,0c0,10.4-7.8,16.6-18.2,17.7
			l20.8,27h-5.7l-19.8-26l0,0h-20.3v26h-4.7v-62.4H319.7z M345.7,832.5c10.4,0,18.2-5.2,18.2-14.6l0,0c0-8.3-6.8-13.5-18.2-13.5
			h-21.3v28.1L345.7,832.5L345.7,832.5z"/>
		
			<linearGradient id="SVGID_4_" gradientUnits="userSpaceOnUse" x1="33.8798" y1="855.7" x2="236.3007" y2="855.7" gradientTransform="matrix(5.1987 0 0 -5.1987 -3.1336 5279.9111)">
			<stop  offset="0" style="stop-color:#95A3FC"/>
			<stop  offset="2.983357e-02" style="stop-color:#82BFFB"/>
			<stop  offset="0.2927" style="stop-color:#51A6E9"/>
			<stop  offset="0.3265" style="stop-color:#43AED0"/>
			<stop  offset="0.3631" style="stop-color:#3AABC1"/>
			<stop  offset="0.3968" style="stop-color:#2799AD"/>
			<stop  offset="0.4306" style="stop-color:#2293A8"/>
			<stop  offset="0.4607" style="stop-color:#18879E"/>
			<stop  offset="0.5106" style="stop-color:#0F7397"/>
			<stop  offset="0.5495" style="stop-color:#0F7397"/>
			<stop  offset="0.589" style="stop-color:#0F7397"/>
			<stop  offset="0.6393" style="stop-color:#1A71A7"/>
			<stop  offset="0.68" style="stop-color:#2C71B3"/>
			<stop  offset="0.685" style="stop-color:#0F7696"/>
			<stop  offset="0.7185" style="stop-color:#6275D5"/>
			<stop  offset="0.739" style="stop-color:#6275D5"/>
			<stop  offset="0.7889" style="stop-color:#B350F5"/>
			<stop  offset="0.8268" style="stop-color:#C449F7"/>
			<stop  offset="0.9021" style="stop-color:#D957FE"/>
			<stop  offset="0.9792" style="stop-color:#E05DFE"/>
			<stop  offset="1" style="stop-color:#EC64FE"/>
		</linearGradient>
		<path fill="url(#SVGID_4_)" d="M429.9,804.4h-21.8v-4.2h48.3v4.2h-21.8v58.2h-4.7L429.9,804.4L429.9,804.4z"/>
		
			<linearGradient id="SVGID_5_" gradientUnits="userSpaceOnUse" x1="33.8798" y1="855.85" x2="236.3007" y2="855.85" gradientTransform="matrix(5.1987 0 0 -5.1987 -3.1336 5279.9111)">
			<stop  offset="0" style="stop-color:#95A3FC"/>
			<stop  offset="2.983357e-02" style="stop-color:#82BFFB"/>
			<stop  offset="0.2927" style="stop-color:#51A6E9"/>
			<stop  offset="0.3265" style="stop-color:#43AED0"/>
			<stop  offset="0.3631" style="stop-color:#3AABC1"/>
			<stop  offset="0.3968" style="stop-color:#2799AD"/>
			<stop  offset="0.4306" style="stop-color:#2293A8"/>
			<stop  offset="0.4607" style="stop-color:#18879E"/>
			<stop  offset="0.5106" style="stop-color:#0F7397"/>
			<stop  offset="0.5495" style="stop-color:#0F7397"/>
			<stop  offset="0.589" style="stop-color:#0F7397"/>
			<stop  offset="0.6393" style="stop-color:#1A71A7"/>
			<stop  offset="0.68" style="stop-color:#2C71B3"/>
			<stop  offset="0.685" style="stop-color:#0F7696"/>
			<stop  offset="0.7185" style="stop-color:#6275D5"/>
			<stop  offset="0.739" style="stop-color:#6275D5"/>
			<stop  offset="0.7889" style="stop-color:#B350F5"/>
			<stop  offset="0.8268" style="stop-color:#C449F7"/>
			<stop  offset="0.9021" style="stop-color:#D957FE"/>
			<stop  offset="0.9792" style="stop-color:#E05DFE"/>
			<stop  offset="1" style="stop-color:#EC64FE"/>
		</linearGradient>
		<path fill="url(#SVGID_5_)" d="M477.2,799.7h44.7v4.2h-40v24.4h35.9v4.2h-35.9v25h40.5v4.2h-45.2L477.2,799.7L477.2,799.7z"/>
		
			<linearGradient id="SVGID_6_" gradientUnits="userSpaceOnUse" x1="33.8798" y1="855.7986" x2="236.3007" y2="855.7986" gradientTransform="matrix(5.1987 0 0 -5.1987 -3.1336 5279.9111)">
			<stop  offset="0" style="stop-color:#95A3FC"/>
			<stop  offset="2.983357e-02" style="stop-color:#82BFFB"/>
			<stop  offset="0.2927" style="stop-color:#51A6E9"/>
			<stop  offset="0.3265" style="stop-color:#43AED0"/>
			<stop  offset="0.3631" style="stop-color:#3AABC1"/>
			<stop  offset="0.3968" style="stop-color:#2799AD"/>
			<stop  offset="0.4306" style="stop-color:#2293A8"/>
			<stop  offset="0.4607" style="stop-color:#18879E"/>
			<stop  offset="0.5106" style="stop-color:#0F7397"/>
			<stop  offset="0.5495" style="stop-color:#0F7397"/>
			<stop  offset="0.589" style="stop-color:#0F7397"/>
			<stop  offset="0.6393" style="stop-color:#1A71A7"/>
			<stop  offset="0.68" style="stop-color:#2C71B3"/>
			<stop  offset="0.685" style="stop-color:#0F7696"/>
			<stop  offset="0.7185" style="stop-color:#6275D5"/>
			<stop  offset="0.739" style="stop-color:#6275D5"/>
			<stop  offset="0.7889" style="stop-color:#B350F5"/>
			<stop  offset="0.8268" style="stop-color:#C449F7"/>
			<stop  offset="0.9021" style="stop-color:#D957FE"/>
			<stop  offset="0.9792" style="stop-color:#E05DFE"/>
			<stop  offset="1" style="stop-color:#EC64FE"/>
		</linearGradient>
		<path fill="url(#SVGID_6_)" d="M541.2,831.4L541.2,831.4c0-17.7,13.5-32.8,31.2-32.8c11.4,0,17.7,4.2,24.4,9.9l-3.1,3.6
			c-5.7-5.2-12-9.4-21.3-9.4c-15.1,0-26.5,12.5-26.5,28.1l0,0c0,16.1,11.4,28.1,26.5,28.1c8.8,0,15.1-3.6,21.8-9.9l3.1,3.1
			c-6.8,6.8-14,10.9-25,10.9C554.7,863.6,541.2,849.6,541.2,831.4z"/>
		
			<linearGradient id="SVGID_7_" gradientUnits="userSpaceOnUse" x1="33.8798" y1="855.75" x2="236.3007" y2="855.75" gradientTransform="matrix(5.1987 0 0 -5.1987 -3.1336 5279.9111)">
			<stop  offset="0" style="stop-color:#95A3FC"/>
			<stop  offset="2.983357e-02" style="stop-color:#82BFFB"/>
			<stop  offset="0.2927" style="stop-color:#51A6E9"/>
			<stop  offset="0.3265" style="stop-color:#43AED0"/>
			<stop  offset="0.3631" style="stop-color:#3AABC1"/>
			<stop  offset="0.3968" style="stop-color:#2799AD"/>
			<stop  offset="0.4306" style="stop-color:#2293A8"/>
			<stop  offset="0.4607" style="stop-color:#18879E"/>
			<stop  offset="0.5106" style="stop-color:#0F7397"/>
			<stop  offset="0.5495" style="stop-color:#0F7397"/>
			<stop  offset="0.589" style="stop-color:#0F7397"/>
			<stop  offset="0.6393" style="stop-color:#1A71A7"/>
			<stop  offset="0.68" style="stop-color:#2C71B3"/>
			<stop  offset="0.685" style="stop-color:#0F7696"/>
			<stop  offset="0.7185" style="stop-color:#6275D5"/>
			<stop  offset="0.739" style="stop-color:#6275D5"/>
			<stop  offset="0.7889" style="stop-color:#B350F5"/>
			<stop  offset="0.8268" style="stop-color:#C449F7"/>
			<stop  offset="0.9021" style="stop-color:#D957FE"/>
			<stop  offset="0.9792" style="stop-color:#E05DFE"/>
			<stop  offset="1" style="stop-color:#EC64FE"/>
		</linearGradient>
		<path fill="url(#SVGID_7_)" d="M617.1,799.7h4.7v29.1h40v-29.1h4.7v62.9h-4.7V833h-40v29.6h-4.7V799.7z"/>
		
			<linearGradient id="SVGID_8_" gradientUnits="userSpaceOnUse" x1="33.8798" y1="855.75" x2="236.3007" y2="855.75" gradientTransform="matrix(5.1987 0 0 -5.1987 -3.1336 5279.9111)">
			<stop  offset="0" style="stop-color:#95A3FC"/>
			<stop  offset="2.983357e-02" style="stop-color:#82BFFB"/>
			<stop  offset="0.2927" style="stop-color:#51A6E9"/>
			<stop  offset="0.3265" style="stop-color:#43AED0"/>
			<stop  offset="0.3631" style="stop-color:#3AABC1"/>
			<stop  offset="0.3968" style="stop-color:#2799AD"/>
			<stop  offset="0.4306" style="stop-color:#2293A8"/>
			<stop  offset="0.4607" style="stop-color:#18879E"/>
			<stop  offset="0.5106" style="stop-color:#0F7397"/>
			<stop  offset="0.5495" style="stop-color:#0F7397"/>
			<stop  offset="0.589" style="stop-color:#0F7397"/>
			<stop  offset="0.6393" style="stop-color:#1A71A7"/>
			<stop  offset="0.68" style="stop-color:#2C71B3"/>
			<stop  offset="0.685" style="stop-color:#0F7696"/>
			<stop  offset="0.7185" style="stop-color:#6275D5"/>
			<stop  offset="0.739" style="stop-color:#6275D5"/>
			<stop  offset="0.7889" style="stop-color:#B350F5"/>
			<stop  offset="0.8268" style="stop-color:#C449F7"/>
			<stop  offset="0.9021" style="stop-color:#D957FE"/>
			<stop  offset="0.9792" style="stop-color:#E05DFE"/>
			<stop  offset="1" style="stop-color:#EC64FE"/>
		</linearGradient>
		<path fill="url(#SVGID_8_)" d="M691.9,799.7h4.2l43.1,54.6v-54.6h4.7v62.9h-3.6L696.1,807v55.6h-4.7v-62.9H691.9z"/>
		
			<linearGradient id="SVGID_9_" gradientUnits="userSpaceOnUse" x1="33.8798" y1="855.7988" x2="236.3007" y2="855.7988" gradientTransform="matrix(5.1987 0 0 -5.1987 -3.1336 5279.9111)">
			<stop  offset="0" style="stop-color:#95A3FC"/>
			<stop  offset="2.983357e-02" style="stop-color:#82BFFB"/>
			<stop  offset="0.2927" style="stop-color:#51A6E9"/>
			<stop  offset="0.3265" style="stop-color:#43AED0"/>
			<stop  offset="0.3631" style="stop-color:#3AABC1"/>
			<stop  offset="0.3968" style="stop-color:#2799AD"/>
			<stop  offset="0.4306" style="stop-color:#2293A8"/>
			<stop  offset="0.4607" style="stop-color:#18879E"/>
			<stop  offset="0.5106" style="stop-color:#0F7397"/>
			<stop  offset="0.5495" style="stop-color:#0F7397"/>
			<stop  offset="0.589" style="stop-color:#0F7397"/>
			<stop  offset="0.6393" style="stop-color:#1A71A7"/>
			<stop  offset="0.68" style="stop-color:#2C71B3"/>
			<stop  offset="0.685" style="stop-color:#0F7696"/>
			<stop  offset="0.7185" style="stop-color:#6275D5"/>
			<stop  offset="0.739" style="stop-color:#6275D5"/>
			<stop  offset="0.7889" style="stop-color:#B350F5"/>
			<stop  offset="0.8268" style="stop-color:#C449F7"/>
			<stop  offset="0.9021" style="stop-color:#D957FE"/>
			<stop  offset="0.9792" style="stop-color:#E05DFE"/>
			<stop  offset="1" style="stop-color:#EC64FE"/>
		</linearGradient>
		<path fill="url(#SVGID_9_)" d="M766.8,831.4L766.8,831.4c0-17.2,12.5-32.8,31.7-32.8s31.2,15.1,31.2,32.2l0,0
			c0,17.2-12.5,32.2-31.7,32.2C779.3,863.6,766.8,848.6,766.8,831.4z M825,831.4L825,831.4c0-15.6-11.4-28.6-27-28.6
			c-15.6,0-26.5,12.5-26.5,28.1l0,0c0,15.6,11.4,28.1,27,28.1C814.1,859.5,825,847,825,831.4z"/>
		
			<linearGradient id="SVGID_10_" gradientUnits="userSpaceOnUse" x1="33.8798" y1="855.8" x2="236.3007" y2="855.8" gradientTransform="matrix(5.1987 0 0 -5.1987 -3.1336 5279.9111)">
			<stop  offset="0" style="stop-color:#95A3FC"/>
			<stop  offset="2.983357e-02" style="stop-color:#82BFFB"/>
			<stop  offset="0.2927" style="stop-color:#51A6E9"/>
			<stop  offset="0.3265" style="stop-color:#43AED0"/>
			<stop  offset="0.3631" style="stop-color:#3AABC1"/>
			<stop  offset="0.3968" style="stop-color:#2799AD"/>
			<stop  offset="0.4306" style="stop-color:#2293A8"/>
			<stop  offset="0.4607" style="stop-color:#18879E"/>
			<stop  offset="0.5106" style="stop-color:#0F7397"/>
			<stop  offset="0.5495" style="stop-color:#0F7397"/>
			<stop  offset="0.589" style="stop-color:#0F7397"/>
			<stop  offset="0.6393" style="stop-color:#1A71A7"/>
			<stop  offset="0.68" style="stop-color:#2C71B3"/>
			<stop  offset="0.685" style="stop-color:#0F7696"/>
			<stop  offset="0.7185" style="stop-color:#6275D5"/>
			<stop  offset="0.739" style="stop-color:#6275D5"/>
			<stop  offset="0.7889" style="stop-color:#B350F5"/>
			<stop  offset="0.8268" style="stop-color:#C449F7"/>
			<stop  offset="0.9021" style="stop-color:#D957FE"/>
			<stop  offset="0.9792" style="stop-color:#E05DFE"/>
			<stop  offset="1" style="stop-color:#EC64FE"/>
		</linearGradient>
		<path fill="url(#SVGID_10_)" d="M852.6,799.7h4.7v58.2h36.9v4.2h-41.6V799.7z"/>
		
			<linearGradient id="SVGID_11_" gradientUnits="userSpaceOnUse" x1="33.8798" y1="855.7988" x2="236.3007" y2="855.7988" gradientTransform="matrix(5.1987 0 0 -5.1987 -3.1336 5279.9111)">
			<stop  offset="0" style="stop-color:#95A3FC"/>
			<stop  offset="2.983357e-02" style="stop-color:#82BFFB"/>
			<stop  offset="0.2927" style="stop-color:#51A6E9"/>
			<stop  offset="0.3265" style="stop-color:#43AED0"/>
			<stop  offset="0.3631" style="stop-color:#3AABC1"/>
			<stop  offset="0.3968" style="stop-color:#2799AD"/>
			<stop  offset="0.4306" style="stop-color:#2293A8"/>
			<stop  offset="0.4607" style="stop-color:#18879E"/>
			<stop  offset="0.5106" style="stop-color:#0F7397"/>
			<stop  offset="0.5495" style="stop-color:#0F7397"/>
			<stop  offset="0.589" style="stop-color:#0F7397"/>
			<stop  offset="0.6393" style="stop-color:#1A71A7"/>
			<stop  offset="0.68" style="stop-color:#2C71B3"/>
			<stop  offset="0.685" style="stop-color:#0F7696"/>
			<stop  offset="0.7185" style="stop-color:#6275D5"/>
			<stop  offset="0.739" style="stop-color:#6275D5"/>
			<stop  offset="0.7889" style="stop-color:#B350F5"/>
			<stop  offset="0.8268" style="stop-color:#C449F7"/>
			<stop  offset="0.9021" style="stop-color:#D957FE"/>
			<stop  offset="0.9792" style="stop-color:#E05DFE"/>
			<stop  offset="1" style="stop-color:#EC64FE"/>
		</linearGradient>
		<path fill="url(#SVGID_11_)" d="M908.2,831.4L908.2,831.4c0-17.2,12.5-32.8,31.7-32.8s31.2,15.1,31.2,32.2l0,0
			c0,17.2-12.5,32.2-31.7,32.2C920.7,863.6,908.2,848.6,908.2,831.4z M966.4,831.4L966.4,831.4c0-15.6-11.4-28.6-27-28.6
			c-15.6,0-26.5,12.5-26.5,28.1l0,0c0,15.6,11.4,28.1,27,28.1C955.5,859.5,966.4,847,966.4,831.4z"/>
		
			<linearGradient id="SVGID_12_" gradientUnits="userSpaceOnUse" x1="33.8798" y1="855.75" x2="236.3007" y2="855.75" gradientTransform="matrix(5.1987 0 0 -5.1987 -3.1336 5279.9111)">
			<stop  offset="0" style="stop-color:#95A3FC"/>
			<stop  offset="2.983357e-02" style="stop-color:#82BFFB"/>
			<stop  offset="0.2927" style="stop-color:#51A6E9"/>
			<stop  offset="0.3265" style="stop-color:#43AED0"/>
			<stop  offset="0.3631" style="stop-color:#3AABC1"/>
			<stop  offset="0.3968" style="stop-color:#2799AD"/>
			<stop  offset="0.4306" style="stop-color:#2293A8"/>
			<stop  offset="0.4607" style="stop-color:#18879E"/>
			<stop  offset="0.5106" style="stop-color:#0F7397"/>
			<stop  offset="0.5495" style="stop-color:#0F7397"/>
			<stop  offset="0.589" style="stop-color:#0F7397"/>
			<stop  offset="0.6393" style="stop-color:#1A71A7"/>
			<stop  offset="0.68" style="stop-color:#2C71B3"/>
			<stop  offset="0.685" style="stop-color:#0F7696"/>
			<stop  offset="0.7185" style="stop-color:#6275D5"/>
			<stop  offset="0.739" style="stop-color:#6275D5"/>
			<stop  offset="0.7889" style="stop-color:#B350F5"/>
			<stop  offset="0.8268" style="stop-color:#C449F7"/>
			<stop  offset="0.9021" style="stop-color:#D957FE"/>
			<stop  offset="0.9792" style="stop-color:#E05DFE"/>
			<stop  offset="1" style="stop-color:#EC64FE"/>
		</linearGradient>
		<path fill="url(#SVGID_12_)" d="M991.4,831.4L991.4,831.4c0-17.2,12.5-32.8,31.2-32.8c10.4,0,16.6,3.1,22.9,8.3l-3.1,3.6
			c-4.7-4.2-10.9-7.3-20.3-7.3c-15.1,0-26,13-26,28.1l0,0c0,16.1,9.9,28.1,27,28.1c7.8,0,15.6-3.1,19.8-7.3V834h-20.8v-4.2h25.5
			v24.4c-5.7,5.2-14.6,9.4-24.4,9.4C1003.3,863.6,991.4,849.1,991.4,831.4z"/>
		
			<linearGradient id="SVGID_13_" gradientUnits="userSpaceOnUse" x1="33.8798" y1="855.75" x2="236.3007" y2="855.75" gradientTransform="matrix(5.1987 0 0 -5.1987 -3.1336 5279.9111)">
			<stop  offset="0" style="stop-color:#95A3FC"/>
			<stop  offset="2.983357e-02" style="stop-color:#82BFFB"/>
			<stop  offset="0.2927" style="stop-color:#51A6E9"/>
			<stop  offset="0.3265" style="stop-color:#43AED0"/>
			<stop  offset="0.3631" style="stop-color:#3AABC1"/>
			<stop  offset="0.3968" style="stop-color:#2799AD"/>
			<stop  offset="0.4306" style="stop-color:#2293A8"/>
			<stop  offset="0.4607" style="stop-color:#18879E"/>
			<stop  offset="0.5106" style="stop-color:#0F7397"/>
			<stop  offset="0.5495" style="stop-color:#0F7397"/>
			<stop  offset="0.589" style="stop-color:#0F7397"/>
			<stop  offset="0.6393" style="stop-color:#1A71A7"/>
			<stop  offset="0.68" style="stop-color:#2C71B3"/>
			<stop  offset="0.685" style="stop-color:#0F7696"/>
			<stop  offset="0.7185" style="stop-color:#6275D5"/>
			<stop  offset="0.739" style="stop-color:#6275D5"/>
			<stop  offset="0.7889" style="stop-color:#B350F5"/>
			<stop  offset="0.8268" style="stop-color:#C449F7"/>
			<stop  offset="0.9021" style="stop-color:#D957FE"/>
			<stop  offset="0.9792" style="stop-color:#E05DFE"/>
			<stop  offset="1" style="stop-color:#EC64FE"/>
		</linearGradient>
		<path fill="url(#SVGID_13_)" d="M1072,799.7h4.7v62.9h-4.7V799.7z"/>
		
			<linearGradient id="SVGID_14_" gradientUnits="userSpaceOnUse" x1="33.8798" y1="855.85" x2="236.3007" y2="855.85" gradientTransform="matrix(5.1987 0 0 -5.1987 -3.1336 5279.9111)">
			<stop  offset="0" style="stop-color:#95A3FC"/>
			<stop  offset="2.983357e-02" style="stop-color:#82BFFB"/>
			<stop  offset="0.2927" style="stop-color:#51A6E9"/>
			<stop  offset="0.3265" style="stop-color:#43AED0"/>
			<stop  offset="0.3631" style="stop-color:#3AABC1"/>
			<stop  offset="0.3968" style="stop-color:#2799AD"/>
			<stop  offset="0.4306" style="stop-color:#2293A8"/>
			<stop  offset="0.4607" style="stop-color:#18879E"/>
			<stop  offset="0.5106" style="stop-color:#0F7397"/>
			<stop  offset="0.5495" style="stop-color:#0F7397"/>
			<stop  offset="0.589" style="stop-color:#0F7397"/>
			<stop  offset="0.6393" style="stop-color:#1A71A7"/>
			<stop  offset="0.68" style="stop-color:#2C71B3"/>
			<stop  offset="0.685" style="stop-color:#0F7696"/>
			<stop  offset="0.7185" style="stop-color:#6275D5"/>
			<stop  offset="0.739" style="stop-color:#6275D5"/>
			<stop  offset="0.7889" style="stop-color:#B350F5"/>
			<stop  offset="0.8268" style="stop-color:#C449F7"/>
			<stop  offset="0.9021" style="stop-color:#D957FE"/>
			<stop  offset="0.9792" style="stop-color:#E05DFE"/>
			<stop  offset="1" style="stop-color:#EC64FE"/>
		</linearGradient>
		<path fill="url(#SVGID_14_)" d="M1102.6,799.7h44.7v4.2h-40v24.4h35.9v4.2h-35.9v25h40.5v4.2h-45.2V799.7z"/>
		
			<linearGradient id="SVGID_15_" gradientUnits="userSpaceOnUse" x1="33.8798" y1="855.8331" x2="236.3007" y2="855.8331" gradientTransform="matrix(5.1987 0 0 -5.1987 -3.1336 5279.9111)">
			<stop  offset="0" style="stop-color:#95A3FC"/>
			<stop  offset="2.983357e-02" style="stop-color:#82BFFB"/>
			<stop  offset="0.2927" style="stop-color:#51A6E9"/>
			<stop  offset="0.3265" style="stop-color:#43AED0"/>
			<stop  offset="0.3631" style="stop-color:#3AABC1"/>
			<stop  offset="0.3968" style="stop-color:#2799AD"/>
			<stop  offset="0.4306" style="stop-color:#2293A8"/>
			<stop  offset="0.4607" style="stop-color:#18879E"/>
			<stop  offset="0.5106" style="stop-color:#0F7397"/>
			<stop  offset="0.5495" style="stop-color:#0F7397"/>
			<stop  offset="0.589" style="stop-color:#0F7397"/>
			<stop  offset="0.6393" style="stop-color:#1A71A7"/>
			<stop  offset="0.68" style="stop-color:#2C71B3"/>
			<stop  offset="0.685" style="stop-color:#0F7696"/>
			<stop  offset="0.7185" style="stop-color:#6275D5"/>
			<stop  offset="0.739" style="stop-color:#6275D5"/>
			<stop  offset="0.7889" style="stop-color:#B350F5"/>
			<stop  offset="0.8268" style="stop-color:#C449F7"/>
			<stop  offset="0.9021" style="stop-color:#D957FE"/>
			<stop  offset="0.9792" style="stop-color:#E05DFE"/>
			<stop  offset="1" style="stop-color:#EC64FE"/>
		</linearGradient>
		<path fill="url(#SVGID_15_)" d="M1165.5,853.2l3.1-3.6c6.8,6.2,13.5,9.4,22.4,9.4c9.4,0,16.1-5.2,16.1-12.5l0,0
			c0-6.8-3.6-10.4-17.7-13.5c-15.1-3.1-21.3-8.3-21.3-17.7l0,0c0-9.4,8.3-16.6,20.3-16.6c9.4,0,15.1,2.6,21.3,7.8l-3.1,3.6
			c-5.7-5.2-12-7.3-18.7-7.3c-9.4,0-15.1,5.2-15.1,12l0,0c0,6.8,3.6,10.9,18.2,13.5c14.6,3.1,20.8,8.3,20.8,17.2l0,0
			c0,9.9-8.8,17.2-20.8,17.2C1180.6,863.6,1172.8,860,1165.5,853.2z"/>
	</g>
</g>
<linearGradient id="SVGID_16_" gradientUnits="userSpaceOnUse" x1="135.8" y1="918.8" x2="76.4" y2="978.2" gradientTransform="matrix(5.1987 0 0 -5.1987 1.330385e-04 5290.3081)">
	<stop  offset="5.259006e-02" style="stop-color:#7B4098"/>
	<stop  offset="0.348" style="stop-color:#4E499D"/>
	<stop  offset="0.6138" style="stop-color:#4870AD"/>
	<stop  offset="0.6275" style="stop-color:#4A78B1"/>
	<stop  offset="0.698" style="stop-color:#549AC1"/>
	<stop  offset="0.7648" style="stop-color:#5BB3CC"/>
	<stop  offset="0.8257" style="stop-color:#60C2D4"/>
	<stop  offset="0.8755" style="stop-color:#61C7D6"/>
</linearGradient>
<path fill="url(#SVGID_16_)" d="M675.3,416.6L675.3,416.6H536V223.2c0-1.6,0.5-2.6,2.1-2.6c1,0,2.6,0.5,3.6,2.1
	c1,1.6,19.8,30.7,19.8,30.7v-15.1l-38-59.3l0,0l-39-61.3v71.7l0,0V416l0,0V467h52l0,0h125.3l0,0h34.8c1,0,2.6,0.5,3.6,2.1
	c1,1.6,19.8,30.7,19.8,30.7v-14.6L675.3,416.6z"/>
<linearGradient id="SVGID_17_" gradientUnits="userSpaceOnUse" x1="182.372" y1="902.172" x2="122.372" y2="962.172" gradientTransform="matrix(5.1987 0 0 -5.1987 1.330385e-04 5290.3081)">
	<stop  offset="9.729064e-02" style="stop-color:#D2A36F"/>
	<stop  offset="0.16" style="stop-color:#C8816A"/>
	<stop  offset="0.2312" style="stop-color:#BF6065"/>
	<stop  offset="0.2704" style="stop-color:#BB5463"/>
	<stop  offset="0.4316" style="stop-color:#AF3E8A"/>
	<stop  offset="0.5611" style="stop-color:#7B4098"/>
	<stop  offset="0.8777" style="stop-color:#4E499D"/>
</linearGradient>
<path fill="url(#SVGID_17_)" d="M780.8,308.9c0,0-150.2,0-165.3,0l19.2,30.2l31.7,49.9l6.2,9.9v-13v-0.5l-2.6-4.7
	c-4.7-7.3-8.8-14.6-9.4-15.1c-1-1.6-1-3.1-0.5-4.2c0.5-1,2.1-1.6,4.2-2.1h112.3c38,0,60.8,26,60.8,57.2v14.6
	c0,29.1-28.1,54.6-65,54.6l-43.7-1l38,60.3l92.5,144V575.1l-30.7-47.3c33.8-1,65.5-53.5,65.5-100.3V414
	C893.7,347.9,846.3,308.9,780.8,308.9z"/>
<g id="Layer_2">
</g>
<linearGradient id="SVGID_18_" gradientUnits="userSpaceOnUse" x1="421.66" y1="918.8" x2="362.26" y2="978.2" gradientTransform="matrix(5.1987 0 0 -5.1987 1.330385e-04 5290.3081)">
	<stop  offset="5.259006e-02" style="stop-color:#7B4098"/>
	<stop  offset="0.348" style="stop-color:#4E499D"/>
	<stop  offset="0.6138" style="stop-color:#4870AD"/>
	<stop  offset="0.6275" style="stop-color:#4A78B1"/>
	<stop  offset="0.698" style="stop-color:#549AC1"/>
	<stop  offset="0.7648" style="stop-color:#5BB3CC"/>
	<stop  offset="0.8257" style="stop-color:#60C2D4"/>
	<stop  offset="0.8755" style="stop-color:#61C7D6"/>
</linearGradient>
<path fill="url(#SVGID_18_)" d="M2161.4,416.6L2161.4,416.6h-139.3V223.2c0-1.6,0.5-2.6,2.1-2.6c1,0,2.6,0.5,3.6,2.1
	c1,1.6,19.8,30.7,19.8,30.7v-15.1l-38-59.3l0,0l-39-61.3v71.7l0,0V416l0,0V467h52l0,0h125.3l0,0h34.8c1,0,2.6,0.5,3.6,2.1
	c1,1.6,19.8,30.7,19.8,30.7v-14.6L2161.4,416.6z"/>
<linearGradient id="SVGID_19_" gradientUnits="userSpaceOnUse" x1="468.232" y1="902.172" x2="408.232" y2="962.172" gradientTransform="matrix(5.1987 0 0 -5.1987 1.330385e-04 5290.3081)">
	<stop  offset="9.729064e-02" style="stop-color:#D2A36F"/>
	<stop  offset="0.16" style="stop-color:#C8816A"/>
	<stop  offset="0.2312" style="stop-color:#BF6065"/>
	<stop  offset="0.2704" style="stop-color:#BB5463"/>
	<stop  offset="0.4316" style="stop-color:#AF3E8A"/>
	<stop  offset="0.5611" style="stop-color:#7B4098"/>
	<stop  offset="0.8777" style="stop-color:#4E499D"/>
</linearGradient>
<path fill="url(#SVGID_19_)" d="M2266.9,308.9c0,0-150.2,0-165.3,0l19.2,30.2l31.7,49.9l6.2,9.9v-13v-0.5l-2.6-4.7
	c-4.7-7.3-8.8-14.6-9.4-15.1c-1-1.6-1-3.1-0.5-4.2c0.5-1,2.1-1.6,4.2-2.1h112.3c38,0,60.8,26,60.8,57.2v14.6
	c0,29.1-28.1,54.6-65,54.6l-43.7-1l38,60.3l92.5,144V575.1l-30.7-47.3c33.8-1,65.5-53.5,65.5-100.3V414
	C2379.7,347.9,2332.4,308.9,2266.9,308.9z"/>
<g id="Layer_2_1_">
</g>
</svg>
